# Use const version of nginx in case future versions won't be able to do sth from the bottom.
FROM nginx:1.23.2

# If ARG won't be passed it should be a hint.
ARG WWW_SERVER_IP='Ip has not been passed in build docker image.'
RUN apt-get update
RUN apt-get install -y systemctl
RUN apt-get install -y nano
RUN apt-get install -y net-tools
RUN sed -i "13 i\    location /www_server {proxy_pass http://$WWW_SERVER_IP:8080/;}" /etc/nginx/conf.d/default.conf
